version: '2'
services:
######################################
# SonarQube Container
######################################
  sonarqube:
    container_name: sonarqube
    network_mode: bridge
    image: petronetto/sonarqube-alpine
    ports:
      - 9000:9000
      - 9002:9002
    volumes:
      - ./samples:/data/samples
      - ./sonar-runner.properties:/opt/sonar-scanner-2.5.1/conf/sonar-runner.properties